batch_size: 10
iters: 30000

train_dataset:
  type: Dataset
  dataset_root: data_orig
  train_path: data_orig/train.txt
  num_classes: 2
  transforms:
    - type: Resize
      target_size: [576,576]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: data_orig
  val_path: data_orig/val.txt
  num_classes: 2
  transforms:
    - type: Resize
      target_size: [576,576]
    - type: Normalize
  mode: val

export:
  transforms:
    - type: Resize
      target_size: [576,576]
    - type: Normalize


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0005

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.04
  end_lr: 0
  power: 0.9


model:
  type: U2Netp
  num_classes: 2
  pretrained: Null

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 1, 1, 1, 1, 1, 1]
